In [1]:
import pandas as pd
import numpy as np

In [80]:
df = pd.read_csv("/home/mintik/Документы/JCMB_2018_Mar.csv")

/tmp/ipykernel_16851/3358807275.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/mintik/Документы/JCMB_2018_Mar.csv")

In [73]:
print(df.dtypes)

TOA5                     object
CR1000                   object
CR1000.1                 object
E8296                    object
CR1000.Std.27            object
CPU:jcmb_21082015.CR1    object
12305                    object
Weather                  object
dtype: object

In [74]:
df.columns

Index(['TOA5', 'CR1000', 'CR1000.1', 'E8296', 'CR1000.Std.27',
       'CPU:jcmb_21082015.CR1', '12305', 'Weather'],
      dtype='object')

In [18]:
df.head(1000).to_csv("pervie_1000_strok.csv", index=False)

In [19]:
df = pd.read_csv("/home/mintik/pervie_1000_strok.csv")

In [54]:
df.columns

Index(['TOA5', 'CR1000', 'CR1000.1', 'E8296', 'CR1000.Std.27',
       'CPU:jcmb_21082015.CR1', '12305', 'Weather'],
      dtype='object')

In [55]:
df.head(25)

,,,,,,,,,,TOA5,CR1000,CR1000.1,E8296,CR1000.Std.27,CPU:jcmb_21082015.CR1,12305,Weather
TIMESTAMP,RECORD,year,dayofyear,hours,minutes,BattV_Avg,SWtot_Avg,SWdif_Avg,Wdir_Avg,Wavg_Avg,Wmax_Max,Tair_Avg,RHum_Avg,Pair_Avg,Rain,Rintensity_Avg,Hail
TS,RN,NaN,NaN,NaN,NaN,Volts,W/meter,W/meter,degrees,m/s,m/s,deg C,%,Pa,mm,mm/h,hits/cm2
NaN,NaN,Smp,Smp,Smp,Smp,Avg,Avg,Avg,Avg,Avg,Max,Avg,Avg,Avg,Smp,Avg,Smp
2018-03-01 00:00:00,1320521,2018,60,0,0,13.64914,0.3368152,0.3789172,76.83334,3.933333,5.5,-4,89,1011.017,655.35,0,0.1
2018-03-01 00:01:00,1320522,2018,60,0,1,13.65005,0.2947129,0.4210185,88.16666,4.233333,6.1,-4,89,1011.017,655.35,0,0.1
2018-03-01 00:02:00,1320523,2018,60,0,2,13.65097,0.2806787,0.4069841,89,2.733333,4.5,-4,89.03333,1011,655.35,0,0.1
2018-03-01 00:03:00,1320524,2018,60,0,3,13.65005,0.2806785,0.3929498,83.83334,2.933333,6.1,-4,89.1,1011,655.35,0,0.1
2018-03-01 00:04:00,1320525,2018,60,0,4,13.65097,0.2806784,0.4350514,91.83334,4.85,6.5,-4,89.1,1010.967,655.35,0,0.1
2018-03-01 00:05:00,1320526,2018,60,0,5,13.65097,0.2526105,0.4210174,91.5,4.383333,6.7,-4,89.1,1010.967,655.35,0,0.1
2018-03-01 00:06:00,1320527,2018,60,0,6,13.65005,0.2385765,0.4350513,87.66666,3.583333,5.1,-4,89.1,1010.95,655.35,0,0.1
2018-03-01 00:07:00,1320528,2018,60,0,7,13.65021,0.2666443,0.4350512,93.33334,2.95,4.5,-4,89.1,1010.9,655.35,0,0.1
2018-03-01 00:08:00,1320529,2018,60,0,8,13.65224,0.2947121,0.3929495,95.5,3.983333,5.6,-4,89.18333,1010.85,655.35,0,0.1
2018-03-01 00:09:00,1320530,2018,60,0,9,13.65302,0.2526104,0.4210173,94.83334,4.75,6.7,-4,89.19999,1010.833,655.35,0,0.1
2018-03-01 00:10:00,1320531,2018,60,0,10,13.65202,0.1964778,0.3929555,104.1667,3.816667,5.3,-4,89.19999,1010.783,655.35,0,0.1
2018-03-01 00:11:00,1320532,2018,60,0,11,13.65197,0.2526128,0.3789192,99.83334,2.683333,4.8,-4,89.19999,1010.733,655.35,0,0.1
2018-03-01 00:12:00,1320533,2018,60,0,12,13.65193,0.2526118,0.3789177,91,3.566667,5.5,-4,89.19999,1010.683,655.35,0,0.1
2018-03-01 00:13:00,1320534,2018,60,0,13,13.65283,0.2385773,0.350849,91.16666,2.4,4.2,-4,89.19999,1010.6,655.35,0,0.1
2018-03-01 00:14:00,1320535,2018,60,0,14,13.65282,0.2105091,0.3508485,96.16666,1.9,3,-4,89.3,1010.6,655.35,0,0.1
2018-03-01 00:15:00,1320536,2018,60,0,15,13.65281,0.2245429,0.3648821,88.83334,3.583333,6.4,-4,89.28333,1010.65,655.35,0,0.1
2018-03-01 00:16:00,1320537,2018,60,0,16,13.65189,0.2385767,0.3789159,98.33334,3.083333,5.3,-4,89.19999,1010.65,655.35,0,0.1
2018-03-01 00:17:00,1320538,2018,60,0,17,13.6528,0.2806783,0.4069836,97.66666,2.883333,4,-4,89.16666,1010.6,655.35,0,0.1
2018-03-01 00:18:00,1320539,2018,60,0,18,13.65188,0.2526104,0.4069835,88.5,2.983333,5.1,-4,89.1,1010.6,655.35,0,0.1
2018-03-01 00:19:00,1320540,2018,60,0,19,13.6528,0.2385772,0.3508487,82.83334,3.133333,5.2,-4.083333,89,1010.6,655.35,0,0.1
2018-03-01 00:20:00,1320541,2018,60,0,20,13.6528,0.2666481,0.3648868,76.33334,3.066667,4.6,-4.1,88.93333,1010.6,655.35,0,0.1
2018-03-01 00:21:00,1320542,2018,60,0,21,13.6528,0.2947162,0.3648868,87.16666,2.766666,5,-4.1,88.85,1010.6,655.35,0,0.1

In [25]:
df.tail(25)

,TOA5,CR1000,CR1000.1,E8296,CR1000.Std.27,CPU:jcmb_21082015.CR1,12305,Weather
975,2.733333,5.4,-1.8,90.1,1000.683,655.35,0,0.1
976,3.633333,5,-1.8,90.03333,1000.617,655.35,0,0.1
977,4.266666,7.6,-1.8,89.96667,1000.6,655.35,0,0.1
978,4.6,6.4,-1.8,89.85,1000.533,655.35,0,0.1
979,2.85,4.3,-1.8,89.73333,1000.533,655.35,0,0.1
980,4.283333,7.1,-1.8,89.64999,1000.55,655.35,0,0.1
981,3.9,5.9,-1.8,89.53333,1000.517,655.35,0,0.1
982,4.166667,7.1,-1.8,89.35,1000.45,655.35,0,0.1
983,3.45,5.5,-1.8,89.14999,1000.5,655.35,0,0.1
984,4.65,6.2,-1.8,88.94999,1000.467,655.35,0,0.1
985,5.066667,7.2,-1.8,88.71667,1000.533,655.35,0,0.1
986,3.2,4.6,-1.8,88.5,1000.517,655.35,0,0.1
987,3.883333,6.9,-1.8,88.31666,1000.5,655.35,0,0.1
988,4.266666,5.7,-1.716667,88.05,1000.5,655.35,0,0.1
989,3.366667,4.9,-1.7,87.78333,1000.5,655.35,0,0.1
990,3.35,4.9,-1.7,87.56666,1000.483,655.35,0,0.1
991,3.05,5.1,-1.666667,87.41666,1000.5,655.35,0,0.1
992,2.983333,4.3,-1.6,87.21667,1000.433,655.35,0,0.1
993,6.1,9.4,-1.6,86.83334,1000.383,655.35,0,0.1
994,4.333333,6.6,-1.516667,86.36666,1000.4,655.35,0,0.1
995,7.6,10.6,-1.5,86.03333,1000.283,655.35,0,0.1
996,4.816667,8.1,-1.4,85.76666,1000.35,655.35,0,0.1
997,5.916667,10,-1.35,85.56666,1000.4,655.35,0,0.1
998,6.3,8.8,-1.3,85.43333,1000.367,655.35,0,0.1
999,7.516666,11.4,-1.3,85.2,1000.283,655.35,0.03333334,0.1

In [32]:
rows_slice = df.iloc[10:20]

In [33]:
print(rows_slice)

        TOA5 CR1000 CR1000.1     E8296 CR1000.Std.27 CPU:jcmb_21082015.CR1  \
10      2.95    4.5       -4      89.1        1010.9                655.35
11  3.983333    5.6       -4  89.18333       1010.85                655.35
12      4.75    6.7       -4  89.19999      1010.833                655.35
13  3.816667    5.3       -4  89.19999      1010.783                655.35
14  2.683333    4.8       -4  89.19999      1010.733                655.35
15  3.566667    5.5       -4  89.19999      1010.683                655.35
16       2.4    4.2       -4  89.19999        1010.6                655.35
17       1.9      3       -4      89.3        1010.6                655.35
18  3.583333    6.4       -4  89.28333       1010.65                655.35
19  3.083333    5.3       -4  89.19999       1010.65                655.35

   12305 Weather
10     0     0.1
11     0     0.1
12     0     0.1
13     0     0.1
14     0     0.1
15     0     0.1
16     0     0.1
17     0     0.1
18     0     0.1
19     0     0.1

In [36]:
columns_slice = df[['TOA5', 'E8296']]

In [37]:
print(columns_slice)

         TOA5     E8296
0    Wavg_Avg  RHum_Avg
1         m/s         %
2         Avg       Avg
3    3.933333        89
4    4.233333        89
..        ...       ...
995       7.6  86.03333
996  4.816667  85.76666
997  5.916667  85.56666
998       6.3  85.43333
999  7.516666      85.2

[1000 rows x 2 columns]

In [39]:
unique = df['E8296'].nunique()
print(unique)

540

In [40]:
otobrozhenie_unique = df.drop_duplicates(subset=['E8296'])

In [41]:
print(otobrozhenie_unique)

         TOA5    CR1000   CR1000.1     E8296 CR1000.Std.27  \
0    Wavg_Avg  Wmax_Max   Tair_Avg  RHum_Avg      Pair_Avg
1         m/s       m/s      deg C         %            Pa
2         Avg       Max        Avg       Avg           Avg
3    3.933333       5.5         -4        89      1011.017
5    2.733333       4.5         -4  89.03333          1011
..        ...       ...        ...       ...           ...
992  2.983333       4.3       -1.6  87.21667      1000.433
993       6.1       9.4       -1.6  86.83334      1000.383
994  4.333333       6.6  -1.516667  86.36666        1000.4
997  5.916667        10      -1.35  85.56666        1000.4
998       6.3       8.8       -1.3  85.43333      1000.367

    CPU:jcmb_21082015.CR1           12305   Weather
0                    Rain  Rintensity_Avg      Hail
1                      mm            mm/h  hits/cm2
2                     Smp             Avg       Smp
3                  655.35               0       0.1
5                  655.35               0       0.1
..                    ...             ...       ...
992                655.35               0       0.1
993                655.35               0       0.1
994                655.35               0       0.1
997                655.35               0       0.1
998                655.35               0       0.1

[540 rows x 8 columns]

In [44]:
import matplotlib.pyplot as pplt

In [49]:
print(df.columns)

Index(['TOA5', 'CR1000', 'CR1000.1', 'E8296', 'CR1000.Std.27',
       'CPU:jcmb_21082015.CR1', '12305', 'Weather'],
      dtype='object')

In [95]:
df.describe()

,TOA5,CR1000,CR1000.1,E8296,CR1000.Std.27,CPU:jcmb_21082015.CR1,12305,Weather
count,42315,42315,42315,42315,42315,42315,42315,42315
unique,1272,286,2530,5557,6635,6,461,5
top,2.866667,4.4,0,0,0,655.35,0,0.1
freq,158,526,4901,11769,4484,32756,30128,32765

In [93]:
df['TOA5', 'CR1000'].boxplot()

KeyError: ('TOA5', 'CR1000')

In [90]:
df['CR1000.1'].hist()
plt.show()

NameError: name 'plt' is not defined

In [98]:
df

,,,,,,,,,,TOA5,CR1000,CR1000.1,E8296,CR1000.Std.27,CPU:jcmb_21082015.CR1,12305,Weather
TIMESTAMP,RECORD,year,dayofyear,hours,minutes,BattV_Avg,SWtot_Avg,SWdif_Avg,Wdir_Avg,Wavg_Avg,Wmax_Max,Tair_Avg,RHum_Avg,Pair_Avg,Rain,Rintensity_Avg,Hail
TS,RN,NaN,NaN,NaN,NaN,Volts,W/meter,W/meter,degrees,m/s,m/s,deg C,%,Pa,mm,mm/h,hits/cm2
NaN,NaN,Smp,Smp,Smp,Smp,Avg,Avg,Avg,Avg,Avg,Max,Avg,Avg,Avg,Smp,Avg,Smp
2018-03-01 00:00:00,1320521,2018,60,0,0,13.64914,0.3368152,0.3789172,76.83334,3.933333,5.5,-4,89,1011.017,655.35,0,0.1
2018-03-01 00:01:00,1320522,2018,60,0,1,13.65005,0.2947129,0.4210185,88.16666,4.233333,6.1,-4,89,1011.017,655.35,0,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-03-30 10:07:00,1362828,2018,89,10,7,13.44305,46.80751,45.16638,88.5,4.383333,8.4,3.9,79.11666,989.0999,655.35,0.2,0.1
2018-03-30 10:08:00,1362829,2018,89,10,8,13.44305,64.74783,63.70984,77.5,4.183333,6.6,3.833333,79.45,989.0833,655.35,0.0,0.1
2018-03-30 10:09:00,1362830,2018,89,10,9,13.44305,82.22525,79.34975,77.0,3.3,5.9,3.8,79.88333,989.0999,655.35,0.0,0.1
2018-03-30 10:10:00,1362831,2018,89,10,10,13.44305,82.58994,79.88277,80.33334,3.7,5.4,3.8,80.21667,989.1166,655.35,0.0,0.1
2018-03-30 10:11:00,1362832,2018,89,10,11,13.44305,73.02365,72.28024,81.66666,4.333333,6.3,3.75,79.71667,989.0999,655.35,0.0,0.1

In [101]:
df.index

MultiIndex([(          'TIMESTAMP',  'RECORD', 'year', 'dayofyear', ...),
            (                 'TS',      'RN',    nan,         nan, ...),
            (                  nan,       nan,  'Smp',       'Smp', ...),
            ('2018-03-01 00:00:00', '1320521', '2018',        '60', ...),
            ('2018-03-01 00:01:00', '1320522', '2018',        '60', ...),
            ('2018-03-01 00:02:00', '1320523', '2018',        '60', ...),
            ('2018-03-01 00:03:00', '1320524', '2018',        '60', ...),
            ('2018-03-01 00:04:00', '1320525', '2018',        '60', ...),
            ('2018-03-01 00:05:00', '1320526', '2018',        '60', ...),
            ('2018-03-01 00:06:00', '1320527', '2018',        '60', ...),
            ...
            ('2018-03-30 10:02:00',   1362823,   2018,          89, ...),
            ('2018-03-30 10:03:00',   1362824,   2018,          89, ...),
            ('2018-03-30 10:04:00',   1362825,   2018,          89, ...),
            ('2018-03-30 10:05:00',   1362826,   2018,          89, ...),
            ('2018-03-30 10:06:00',   1362827,   2018,          89, ...),
            ('2018-03-30 10:07:00',   1362828,   2018,          89, ...),
            ('2018-03-30 10:08:00',   1362829,   2018,          89, ...),
            ('2018-03-30 10:09:00',   1362830,   2018,          89, ...),
            ('2018-03-30 10:10:00',   1362831,   2018,          89, ...),
            ('2018-03-30 10:11:00',   1362832,   2018,          89, ...)],
           length=42315)

In [102]:
df.stack()

TIMESTAMP            RECORD   year  dayofyear  hours  minutes  BattV_Avg  SWtot_Avg  SWdif_Avg  Wdir_Avg  TOA5                     Wavg_Avg
                                                                                                          CR1000                   Wmax_Max
                                                                                                          CR1000.1                 Tair_Avg
                                                                                                          E8296                    RHum_Avg
                                                                                                          CR1000.Std.27            Pair_Avg
                                                                                                                                     ...
2018-03-30 10:11:00  1362832  2018  89         10     11       13.44305   73.02365   72.28024   81.66666  E8296                    79.71667
                                                                                                          CR1000.Std.27            989.0999
                                                                                                          CPU:jcmb_21082015.CR1      655.35
                                                                                                          12305                         0.0
                                                                                                          Weather                       0.1
Length: 338520, dtype: object